import { errorMiddleware } from "@middleware/error.middleware";
import { logger } from "@shared/logger/logger";
import app from "./app";
import { env } from "@config/env";
import authRoutes from "@modules/auth/auth.routes";
import userRoutes from "@modules/user/user.routes";
import organizationRoutes from "@modules/organization/organization.routes";
import branchRoutes from "@modules/branch/branch.routes";
import roleRoutes from "@modules/user/role/role.routes";
import permissionRoutes from "@modules/user/permission/permission.routes";
import academicTermRoutes from "@modules/academic/academic-term/academic-term.routes";
import academicYearRoutes from "@modules/academic/academic-year/academic-year.routes";
import classroomRoutes from "@modules/academic/classroom/classroom.routes";
import subjectRoutes from "@modules/academic/subject/subject.routes";
import teacherAssignmentRoutes from "@modules/academic/teacher-assignment/teacher-assignment.routes";
import enrollmentRoutes from "@modules/student/enrollment/enrollment.routes";
import guardianRoutes from "@modules/student/guardian/guardian.routes";
import homeroomTeacherRoutes from "@modules/academic/homeroom-teacher/homeroom-teacher.routes";
import schedulePeriodRoutes from "@modules/schedule/period/period.routes";
import timetableEntryRoutes from "@modules/schedule/timetable/timetable.routes";
import studentAttendanceRoutes from "@modules/attendance/student/student-attendance.routes";
import staffAttendanceRoutes from "@modules/attendance/staff/staff-attendance.routes";
import assessmentRoutes from "@modules/assessment/assessment/assessment.routes";
import reportCardRoutes from "@modules/assessment/report-card/report-card.routes";
import feeCategoryRoutes from "@modules/finance/fee/fee-category/fee-category.routes";
import feeStructureRoutes from "@modules/finance/fee/fee-structure/fee-structure.routes";
import invoiceRoutes from "@modules/finance/fee/invoice/invoice.routes";
import paymentRoutes from "@modules/finance/payment/payment.routes";
import salaryStructureRoutes from "@modules/finance/salary/salary-structure/salary-structure.routes";
import salaryPaymentRoutes from "@modules/finance/salary/salary-payment/salary-payment.routes";
import revenueRoutes from "@modules/finance/revenue/revenue.routes";
import expenseRoutes from "@modules/finance/expense/expense.routes";
import financialReportRoutes from "@modules/finance/report/financial-report.routes";
import telegramRoutes from "@modules/notification/gateway/telegram/telegram.routes";
import announcementRoutes from "@modules/notification/announcement/announcement.routes";
import dashboardRoutes from "@modules/dashboard/dashboard.routes";
import communicationRoutes from "@modules/notification/communication/communication.routes";
import { rateLimiters } from "@middleware/rateLimiter.middleware";


app.listen(env.PORT, () => {
  logger.info(`Server running on port ${env.PORT}`);
});
app.use('/api', rateLimiters.api);

app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/organizations", organizationRoutes);
app.use("/api/branches", branchRoutes);
app.use("/api/roles", roleRoutes);
app.use("/api/permissions", permissionRoutes);
app.use("/api/academic-years", academicYearRoutes);
app.use("/api/academic-terms", academicTermRoutes);
app.use("/api/classrooms", classroomRoutes);
app.use("/api/subjects", subjectRoutes);
app.use("/api/teacher-assignments", teacherAssignmentRoutes)
app.use("/api/guardians", guardianRoutes);
app.use("/api/enrollments", enrollmentRoutes);
app.use("/api/homeroom-teachers", homeroomTeacherRoutes);
app.use("/api/schedule-periods", schedulePeriodRoutes);
app.use("/api/timetable-entries", timetableEntryRoutes);
app.use("/api/student-attendance", studentAttendanceRoutes);
app.use("/api/staff-attendance", staffAttendanceRoutes);
app.use("/api/assessments", assessmentRoutes);
app.use("/api/report-cards", reportCardRoutes);
app.use("/api/fee-categories", feeCategoryRoutes);
app.use("/api/fee-structures", feeStructureRoutes);
app.use("/api/invoices", invoiceRoutes);
app.use("/api/payments", paymentRoutes);
app.use("/api/salary-structures", salaryStructureRoutes);
app.use("/api/salary-payments", salaryPaymentRoutes);
app.use("/api/revenues", revenueRoutes);
app.use("/api/expenses", expenseRoutes);
app.use("/api/financial-reports", financialReportRoutes);
app.use('/api/telegram', telegramRoutes);
app.use("/api/announcements", announcementRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/communication', communicationRoutes);

app.use(errorMiddleware);